version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount debug audio directory for persistent storage
      - ./debug_audio:/app/debug_audio
      # Mount ChromaDB data directory
      - ./data/chromadb:/app/data/chromadb
      # Mount logs directory
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
