#!/bin/bash

# SSH Setup and Deployment Guide for Anna Webinar Demo

echo "🔐 SSH Setup and Deployment Guide for Vultr VPS"
echo "==============================================="

VPS_IP="45.32.212.233"
VPS_USER="root"

echo "📋 Before deploying, you need to set up SSH access to the VPS:"
echo ""
echo "Option 1: Use SSH Key (Recommended)"
echo "-----------------------------------"
echo "1. Generate SSH key (if you don't have one):"
echo "   ssh-keygen -t rsa -b 4096 -C 'your-email@example.com'"
echo ""
echo "2. Copy your public key to the VPS:"
echo "   ssh-copy-id ${VPS_USER}@${VPS_IP}"
echo "   (Enter the VPS password when prompted)"
echo ""
echo "3. Test the connection:"
echo "   ssh ${VPS_USER}@${VPS_IP} 'echo \"SSH setup successful\"'"
echo ""

echo "Option 2: Password Authentication"
echo "--------------------------------"
echo "If you prefer password authentication, edit /etc/ssh/sshd_config on the VPS:"
echo "1. Set: PasswordAuthentication yes"
echo "2. Restart SSH: sudo systemctl restart sshd"
echo ""

echo "🧪 Testing SSH Connection..."
if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o BatchMode=yes ${VPS_USER}@${VPS_IP} "echo 'SSH connection successful'" > /dev/null 2>&1; then
    echo "✅ SSH connection works! You can proceed with deployment."
    echo ""
    echo "🚀 Ready to deploy? Run:"
    echo "   ./deploy-to-vultr.sh"
else
    echo "❌ SSH connection failed."
    echo ""
    echo "🔧 Troubleshooting steps:"
    echo "1. Verify VPS IP: ${VPS_IP}"
    echo "2. Check if VPS is running and accessible"
    echo "3. Ensure SSH keys are properly configured"
    echo "4. Try manual SSH connection: ssh ${VPS_USER}@${VPS_IP}"
    echo ""
    echo "📖 Manual deployment alternative:"
    echo "If SSH key setup is problematic, you can deploy manually:"
    echo ""
    echo "1. Build the app locally:"
    echo "   npm run build"
    echo ""
    echo "2. Create a deployment package:"
    echo "   tar -czf anna-webinar-demo.tar.gz build/ Dockerfile nginx.conf docker-compose.yml"
    echo ""
    echo "3. Upload to VPS using SCP or file transfer:"
    echo "   scp anna-webinar-demo.tar.gz ${VPS_USER}@${VPS_IP}:/tmp/"
    echo ""
    echo "4. SSH to VPS and extract:"
    echo "   ssh ${VPS_USER}@${VPS_IP}"
    echo "   cd /opt && tar -xzf /tmp/anna-webinar-demo.tar.gz"
    echo ""
    echo "5. Run Docker commands manually on VPS:"
    echo "   docker build -t anna-webinar-demo ."
    echo "   docker run -d -p 3000:80 anna-webinar-demo"
fi

echo ""
echo "📞 Need help? Check the DEPLOYMENT-README.md for detailed instructions."
