name: Deploy Anna Webinar Demo to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'anna-webinar-demo/**'
      - '.github/workflows/deploy-anna-webinar-demo.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: anna-webinar-demo/package.json

      - name: Install dependencies
        working-directory: anna-webinar-demo
        run: npm ci

      - name: Build React app
        working-directory: anna-webinar-demo
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./anna-webinar-demo/build
          destination_dir: anna-webinar-demo
