name: Deploy Anna Webinar Demo to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'anna-webinar-demo/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'anna-webinar-demo/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd anna-webinar-demo
          npm ci
          
      - name: Build project
        run: |
          cd anna-webinar-demo
          CI=false npm run build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./anna-webinar-demo/build
          publish_branch: gh-pages